name: Backend Develop Deployment

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: backendBuild
      source: Backend Build
      trigger:
        branches:
          include:
            - develop

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        pool:
          name: Default-Windows
        steps:
          - checkout: none
          
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: specific
              project: $(System.TeamProject)
              definition: Backend Build
              buildVersionToDownload: latestFromBranch
              branchName: refs/heads/develop
              artifactName: backend-dist
              downloadPath: $(System.DefaultWorkingDirectory)/backend-dist

          #- task: AzureStaticWebApp@0
          #  inputs:
          #    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
          #    app_location: 'backend-dist'
          #    skip_app_build: true
          #    skip_api_build: true
          #    is_static_export: true