name: Frontend Develop Deployment

resources:
  pipelines:
    - pipeline: frontendBuild
      source: Frontend Develop Build
      trigger: true

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        pool:
          name: Default-Windows
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: specific
              project: $(System.TeamProject)
              definition: Frontend Develop Build
              buildVersionToDownload: latestFromBranch
              branchName: refs/heads/develop
              artifactName: frontend-dist
              downloadPath: $(Pipeline.Workspace)/frontend-dist

          - script: |
              echo "Deploying frontend..."
            displayName: "Deploy Step"