name: Frontend Build

pr:
  branches:
    include:
      - develop
trigger:
  branches:
    include:
      - develop

jobs:
  - job: build
    displayName: Build Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))

    pool:
      name: Default-Windows

    steps:
      - checkout: self
        submodules: true

      - task: NodeTool@0
        inputs:
          versionSpec: '22.x'
        displayName: 'Use Node.js'
      
      - script: |
          mkdir "$(Pipeline.Workspace)\.npm"
          npm config set cache $(Pipeline.Workspace)/.npm --global
        displayName: 'Configure npm cache'

      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | Frontend/package-lock.json'
          path: $(Pipeline.Workspace)/Frontend/.npm
          restoreKeys: |
            npm | "$(Agent.OS)"
        displayName: 'Cache node_modules'

      - script: npm ci
        workingDirectory: Frontend
        displayName: 'Install dependencies'

      - script: npm run build -- --output-path=dist/KnowledgeGraph/browser
        workingDirectory: Frontend
        displayName: 'Build Frontend'
