name: Frontend Production Deployment

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: frontendBuild
      source: Frontend Build
      trigger:
        branches:
          include:
            - develop

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        pool:
          name: Default-Linux
        steps:
          - checkout: none
          
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: specific
              project: $(System.TeamProject)
              definition: Frontend Build
              buildVersionToDownload: latestFromBranch
              branchName: refs/heads/main
              artifactName: frontend-dist
              downloadPath: $(System.DefaultWorkingDirectory)/frontend-dist

          - task: AzureStaticWebApp@0
            inputs:
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
              app_location: 'frontend-dist'
              skip_app_build: true
              skip_api_build: true
              is_static_export: true