name: Frontend Production Deployment

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: frontendBuild
      source: Frontend Production Build
      trigger:
        branches:
          include:
            - main

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        pool:
          name: Default-Linux
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: specific
              project: $(System.TeamProject)
              definition: Frontend Production Build
              buildVersionToDownload: latestFromBranch
              branchName: refs/heads/main
              artifactName: frontend-dist
              downloadPath: $(System.DefaultWorkingDirectory)/frontend-dist

          - script: |
              echo "Artifact contents:"
              ls -R "$(Pipeline.Workspace)/frontend-dist"
            displayName: "Debug artifact contents"

          - task: AzureStaticWebApp@0
            inputs:
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_DEV)
              app_location: 'frontend-dist'
              skip_app_build: true
              skip_api_build: true
              is_static_export: true