name: Frontend Develop Deployment

resources:
  pipelines:
    - pipeline: frontendBuild
      source: Frontend Develop Build
      trigger: true

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        pool:
          name: Default-Linux
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: specific
              project: $(System.TeamProject)
              definition: Frontend Develop Build
              buildVersionToDownload: latestFromBranch
              branchName: refs/heads/develop
              artifactName: frontend-dist
              #downloadPath: $(Pipeline.Workspace)/frontend-dist
              downloadPath: $(System.DefaultWorkingDirectory)/frontend-dist

          #- script: |
          #    if exist "$(Pipeline.Workspace)\frontend-dist\dist.zip" (
          #      del "$(Pipeline.Workspace)\frontend-dist\dist.zip"
          #    )
          #  displayName: 'Remove transport dist.zip'

          #- script: |
          #    echo "Deploying frontend..."
          #    ls -la "$(Pipeline.Workspace)/frontend-dist"
          #  displayName: "Deploy Step"

          #- task: AzureStaticWebApp@0
          #  inputs:
          #    output_location: '$(Pipeline.Workspace)/frontend-dist'
          #    skip_app_build: true
          #    skip_api_build: true
          #    is_static_export: true
          #    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SKY_09F7A7F03)'
          #    production_branch: 'main'


          - script: |
              echo "Artifact contents:"
              ls -R "$(Pipeline.Workspace)/frontend-dist"
            displayName: "Debug artifact contents"


          - task: AzureStaticWebApp@0
            inputs:
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_DEV)
              #app_location: '$(Pipeline.Workspace)/frontend-dist'
              app_location: 'frontend-dist'
              #output_location: 'Output location'
              skip_app_build: true
              skip_api_build: true
              is_static_export: true

              #workingDirectory: 'Working directory'
              #app_build_command: 'App build command'
              #api_build_command: 'Api build command'
              #routes_location: 'Routes location'
              #config_file_location: 'Config file location'
              #build_timeout_in_minutes: Build timeout in minutes
              #deployment_environment: 'Deployment Environment'
              #production_branch: 'Production Branch'
              #data_api_location: 'Data api location'
              #azure_access_token: 'Azure Access Token'
              #default_hostname: 'Default Hostname'