name: Frontend Build Develop

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - Frontend

jobs:
  - job: build
    displayName: Build Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))

    pool:
      name: Default-Windows

    workspace:
      clean: all

    steps:
      - checkout: self
        submodules: true
        clean: true

      - script: |
          echo Cleaning dist folder...
          if exist Frontend\dist rmdir /s /q Frontend\dist
        displayName: 'Clean dist folder'

      - task: NodeTool@0
        inputs:
          versionSpec: '22.x'
        displayName: 'Use Node.js'
      
      - script: |
          mkdir "$(Pipeline.Workspace)\.npm"
          npm config set cache $(Pipeline.Workspace)/.npm --global
        displayName: 'Configure npm cache'

      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | Frontend/package-lock.json'
          path: $(Pipeline.Workspace)/.npm
          restoreKeys: |
            npm | "$(Agent.OS)"
        displayName: 'Cache node_modules'

      - script: npm ci
        workingDirectory: Frontend
        displayName: 'Install dependencies'

      - script: npm run build -- --output-path=dist/KnowledgeGraph
        workingDirectory: Frontend
        displayName: 'Build Frontend'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: Frontend/dist/KnowledgeGraph/browser
          artifact: frontend-dist
        displayName: 'Publish build artifact'