name: Frontend Develop Deployment

resources:
  pipelines:
    - pipeline: frontendBuild
      source: Frontend Develop Build
      trigger: true

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        pool:
          name: Default-Linux
        steps:
          #- task: DownloadPipelineArtifact@2
          #  inputs:
          #    buildType: specific
          #    project: $(System.TeamProject)
          #    definition: Frontend Develop Build
          #    buildVersionToDownload: latestFromBranch
          #    branchName: refs/heads/develop
          #    artifactName: frontend-dist
          #    downloadPath: $(Pipeline.Workspace)/frontend-dist

          #- script: |
          #    if exist "$(Pipeline.Workspace)\frontend-dist\dist.zip" (
          #      del "$(Pipeline.Workspace)\frontend-dist\dist.zip"
          #    )
          #  displayName: 'Remove transport dist.zip'

          - script: |
              echo "Deploying frontend..."
              ls -la "$(Pipeline.Workspace)/frontend-dist"
            displayName: "Deploy Step"

          - task: AzureStaticWebApp@0
            inputs:
              output_location: '$(Pipeline.Workspace)/frontend-dist'
              skip_app_build: true
              skip_api_build: true
              is_static_export: true
              azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SKY_09F7A7F03)'
              production_branch: 'main'